title: Jekyll 文档
description: Rubyist.cn 维护的 Jekyll 中文文档！
theme: just-the-docs

url: https://docs.rubyist.cn/jekyll

aux_links:
  『Rubyist 文集』: https://docs.rubyist.cn
  
callouts:
  warning:
    title: 警告
    color: red
  note:
    title: 备注
    color: blue
  new:
    title: 新！
    color: green
  highlight:
    title: 注意
    color: yellow
  info:
    title: 信息
    color: purple

